// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnjXhc-FRiK9uuA9F5kuxKVFWvwIOamEU',
    appId: '1:782942563807:web:1b369facd80d0950d0686a',
    messagingSenderId: '782942563807',
    projectId: 'alghanmi-shop',
    authDomain: 'alghanmi-shop.firebaseapp.com',
    storageBucket: 'alghanmi-shop.firebasestorage.app',
    measurementId: 'G-TRZE8QL13B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUdZFI2Ns8FYcp4xPPy4iDXyyBxZOq_tk',
    appId: '1:782942563807:android:fe500c1dfa570382d0686a',
    messagingSenderId: '782942563807',
    projectId: 'alghanmi-shop',
    storageBucket: 'alghanmi-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmjwJQjsHS0iE1ORgMh_URcq3O78-RrKE',
    appId: '1:782942563807:ios:e5c607d4408163cad0686a',
    messagingSenderId: '782942563807',
    projectId: 'alghanmi-shop',
    storageBucket: 'alghanmi-shop.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmjwJQjsHS0iE1ORgMh_URcq3O78-RrKE',
    appId: '1:782942563807:ios:e5c607d4408163cad0686a',
    messagingSenderId: '782942563807',
    projectId: 'alghanmi-shop',
    storageBucket: 'alghanmi-shop.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnjXhc-FRiK9uuA9F5kuxKVFWvwIOamEU',
    appId: '1:782942563807:web:2a6bb24ed7131f64d0686a',
    messagingSenderId: '782942563807',
    projectId: 'alghanmi-shop',
    authDomain: 'alghanmi-shop.firebaseapp.com',
    storageBucket: 'alghanmi-shop.firebasestorage.app',
    measurementId: 'G-TK06GBX5TB',
  );
}
